input {
  beats {
    port => 5047
    id => "ExMessageTrackingip_id"
    type => "ExMessageTrackingip"
  }
}
filter {
  if [type] == "ExMessageTrackingip" {
    csv {
      columns => [ 'date-time','client-ip','client-hostname','server-ip','server-hostname','source-context','connector-id','source','event-id','internal-message-id','message-id','network-message-id','recipient-address','recipient-status','total-bytes','recipient-count','related-recipient-address','reference','message-subject','sender-address','return-path','message-info','directionality','tenant-id','original-client-ip','original-server-ip','custom-data','transport-traffic-type','log-id','schema-version' ]
      remove_field => [ "date-time" ]
      remove_field => [ "source-context" ]
    }
    grok {      
        match => [ "message", "%{TIMESTAMP_ISO8601:timestamp}" ]
    }
    geoip {
      source  => "original-client-ip"
      target  => "geoip"
      add_tag => [ "geoip" ]
      add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}"]
      add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}" ]
      
    }
    mutate {
        convert => [ "[geoip][coordinates]", "float" ]
        convert => [ "total-bytes", "integer" ]
        convert => [ "recipient-count", "integer" ]
        split => ["recipient-address", ";"]
        split => [ "custom-data", ";" ]
    }
    date {
        match => [ "timestamp", "ISO8601" ]
        timezone => "Europe/Istanbul"
        remove_field => [ "timestamp" ]
    }
    if "_grokparsefailure" in [tags] {
          drop { }
    }
  }
}
output {
  if [type]== "ExMessageTrackingip"{
     elasticsearch {
       hosts => "localhost:9200"
       index => "ipexmessagetracking-%{+YYYY-MM-dd}"
     }
  }
}