input {
  beats {
    port => 5046
    id => "ExIIS_id"
    type => "ExIIS"
  }
}
filter {
  if [type] == "ExIIS" {
    grok {
      match => ["message", "%{TIMESTAMP_ISO8601:log_timestamp} %{IP:serverIP} %{WORD:method} %{URIPATH:uriStem} %{NOTSPACE:uriQuery} %{NUMBER:port} %{NOTSPACE:username} %{IPORHOST:clientIP} %{NOTSPACE:userAgent} %{NOTSPACE:referer} %{NUMBER:response} %{NUMBER:subresponse} %{NUMBER:win32response} %{NUMBER:timetaken}"]
    }
    date {
      match => [ "log_timestamp", "YYYY-MM-dd HH:mm:ss" ]
        timezone => "Europe/Istanbul"
    }
    if [bytesSent] {
      ruby {
        code => "event['kilobytesSent'] = event['bytesSent'].to_i / 1024.0"
      }
    }
    if [bytesReceived] {
      ruby {
        code => "event['kilobytesReceived'] = event['bytesReceived'].to_i / 1024.0"
      }
    }
    mutate {
      convert => ["timetaken", "integer"]
      add_field => { "clientHostname" => "%{clientIP}" }
      remove_field => [ "log_timestamp"]
    }
    dns {
      action => "replace"
      reverse => ["clientHostname"]
    }
      useragent {
          source=> "useragent"
          prefix=> "browser"
      }
  }
}
output {
   if [type]== "ExIIS"{
     elasticsearch {
       hosts => "localhost:9200"
       index => "exw3c-%{+YYYY-MM-dd}"
     }
  }
}